CREATE DATABASE auth;

CREATE TABLE users (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar(255) NOT NULL,
	last_name varchar(255) NOT NULL,
	date_of_birth varchar(255) NULL,
	address varchar(100) NULL,
	phone_number varchar(50) NULL,
	email varchar(50) NOT NULL,
	document_number varchar(50) NOT NULL,
	role varchar(50) NOT NULL,
	base_salary varchar(255) not null,
	constraint usuario_pk primary key (id)
);
