CREATE TABLE usuario (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar(255) NOT NULL,
	last_name varchar(255) NOT NULL,
	date_of_birth date NULL,
	address varchar(100) NULL,
	phone_number varchar(50) NULL,
	email varchar(50) NOT NULL,
	document_number varchar(50) NOT NULL,
	role_id varchar(50) NOT NULL,
	base_salary numeric(10,2) not null,
	constraint usuario_pk primary key (id)
);
